import { DataTypes } from 'sequelize';
import db from '../config/db.js'

const Company = db.define('companies',{
    code:{
        type:DataTypes.STRING,
        allowNull:false,
        unique:true
    },
    rut:{
        type:DataTypes.STRING,
        allowNull:false,
        unique:true
    },
    name:{
        type:DataTypes.STRING,
        allowNull:false
    },
    sampleLocation:{
        type:DataTypes.STRING,
        allowNull:false
    },
    floorNumber:{
        type:DataTypes.INTEGER
    },
    street:{
        type:DataTypes.STRING,
        allowNull:false
    },
    city:{
        type:DataTypes.STRING,
        allowNull:false
    },
    state:{
        type:DataTypes.STRING,
        allowNull:false
    },
    contactPerson:{
        type:DataTypes.STRING,
        allowNull:true 
    },
    contactPosition:{
        type:DataTypes.STRING,
        allowNull:true 
    },
    phoneNumberOne:{
        type:DataTypes.INTEGER,
        allowNull:false
    },
    numberPhoneCallsOne:{
        type:DataTypes.INTEGER,
        allowNull:false
    },
    phoneNumberSecond:{
        type:DataTypes.INTEGER,
        allowNull:true
    },
    numberPhoneCallsSecond:{
        type:DataTypes.INTEGER,
        allowNull:true
    },
    zipCode:{
        type:DataTypes.STRING,
        allowNull:true 
    },
    faxNumber:{
        type:DataTypes.INTEGER,
        allowNull:true
    },
    preferenceNumber:{
        type:DataTypes.INTEGER,
        allowNull:false
    },
    emailAddress:{
        type:DataTypes.STRING,
        allowNull:true
    },
    web:{
        type:DataTypes.STRING,
        allowNull:true
    },
    use:{
        type:DataTypes.BOOLEAN,
        allowNull:false
    },
})

export default Company